/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MusicLadderController;
import entity.Song;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class MusicLadder extends javax.swing.JFrame
{
    
    private MusicLadderController mlc = null;

    /**
     * Creates new form MusicLadder
     */
    public MusicLadder()
    {
        initComponents();
        initSecondaryComponents();
    }
    
    private void initSecondaryComponents() {
        mlc = MusicLadderController.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSongs = new javax.swing.JTable();
        jButtonGetSongs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String []
            {
                "Name", "Score", "ELO Rating"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSongs);

        jButtonGetSongs.setText("Get Songs");
        jButtonGetSongs.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonGetSongsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGetSongs)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGetSongs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGetSongsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonGetSongsActionPerformed
    {//GEN-HEADEREND:event_jButtonGetSongsActionPerformed
        List<Song> songs = mlc.getSongs();
        populatejTableFriends( songs );
    }//GEN-LAST:event_jButtonGetSongsActionPerformed
    
    public static void clearTable(final JTable table)
    {
        for (int i = 0; i < table.getRowCount(); i++)
        {
            for (int j = 0; j < table.getColumnCount(); j++)
            {
                table.setValueAt("", i, j);
            }
        }
    }
    
    private void populatejTableFriends(List<Song> songs)
    {
        clearTable( jTableSongs );
        String[] friendsTableColumnNames = new String[]
        {
            "Name", "Score", "ELO Rating"
        };
        
        Object[][] data = new Object[songs.size()][6];
        for (int i = 0; i < songs.size(); i++)
        {
            String name = songs.get(i).getName();
            String score = "0-0-0";//listOfFriends.get(i).getFirstMessage();
            Float eloRating = songs.get(i).getCurrentRating();

            data[i][0] = name;
            data[i][1] = score;
            data[i][2] = eloRating;
        }
        
        jTableSongs.setModel(new DefaultTableModel(data, friendsTableColumnNames)
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        });

//        jTableFriends.getColumnModel().getColumn(0).setPreferredWidth(3);
//        jTableFriends.getColumnModel().getColumn(1).setPreferredWidth(10);
//        jTableFriends.getColumnModel().getColumn(2).setPreferredWidth(5);
//        jTableFriends.getColumnModel().getColumn(3).setPreferredWidth(10);
//        jTableFriends.getColumnModel().getColumn(4).setPreferredWidth(10);
//        jTableFriends.getColumnModel().getColumn(5).setPreferredWidth(7);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MusicLadder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MusicLadder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MusicLadder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MusicLadder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MusicLadder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGetSongs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSongs;
    // End of variables declaration//GEN-END:variables
}
